name: Playwright CI

on:
  push:
    branches: [ main, master, sprint-0, sprint-1, sprint-2, sprint-3, sprint-4, sprint-5 ]
  pull_request:
    branches: [ main, master, sprint-0, sprint-1, sprint-2, sprint-3, sprint-4, sprint-5 ]

concurrency:
  group: playwright-${{ github.ref }}
  cancel-in-progress: true

jobs:
  playwright:
    name: E2E Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: digitalbank

    steps:
      # 1 Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2 Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: digitalbank/package-lock.json

      # 3 Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4 Install Playwright browsers (only if not cached)
      - name: Install Playwright
        run: npx playwright install --with-deps

      # 5 Run Smoke Tests (bloque si KO)
      - name: Run Smoke Tests
        run: npx playwright test --project=SmokeTest

      # 6 Run Full Test Suite
      - name: Run Test Suite
        run: npx playwright test --project=TestSuite

      # 7 Upload HTML Report (toujours)
      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: digitalbank/playwright-report/index.html
          retention-days: 30
      # 8 Create Issue if tests failed
      - name: Create GitHub Issue on Failure
        if: failure()
        uses: peter-evans/create-issue-from-file@v6
        with:
          title: "E2E Tests Failed on ${{ github.ref }}"
          content-filepath: digitalbank/playwright-report/index.html
          labels: bug, e2e-tests